### ISSUE TITLE
SENSU_SUBSCRIPTIONS env var appears to be space delimited, not comma delimited

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#1144]
In testing the sample app and attempting to add a 2nd subscription, the env var `SENSU_SUBSCRIPTIONS` allows for space-delimited strings, not comma-delimited. This should be documented. Example:

<details>
  <summary>Sensu Go K8s Daemonset</summary>

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sensu-agent
  labels:
    name: sensu-agent
spec:
  template:
    metadata:
      labels:
        name: sensu-agent
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: sensu-agent
          image: sensu/sensu:latest
          command: ["/opt/sensu/bin/sensu-agent", "start", "--log-level", "debug"]
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SENSU_ID
              value: "kube-node-$(HOST_IP)"
            - name: SENSU_BACKEND_URL
              value: ws://sensu-backend.default.svc.cluster.local:8081
            - name: SENSU_NAMESPACE
              value: demo
            - name: SENSU_SUBSCRIPTIONS
              value: "daemonset proxy"
            - name: SENSU_DEREGISTER
              value: "true"
            - name: SENSU_STATSD_EVENT_HANDLERS
              value: statsd
          ports:
            - containerPort: 3030
              hostPort: 3030
              protocol: TCP
```

</details>

While the above example works, we're using a comma-delimited daemonset in the [classic example here](https://github.com/sensu/sensu-kube-demo/blob/master/classic/deploy/daemonsets/sensu-client-daemonset.yaml#L44-L#45). I'm not sure if this is intended by design. However, this doesn't really seem to jive with the understanding I have of subscriptions being comma-delimited as we see in [the spec attribute examples](https://docs.sensu.io/sensu-go/5.1/reference/entities/#spec-attributes).
