### ISSUE TITLE
Document filter when attributes

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#1423]
Page: Filter reference

To do:

- [ ] Write and test example filter
- [ ] Replace documentation for filter `when` attributes removed in https://github.com/sensu/sensu-docs/pull/920
- [ ] Test and investigate supported versions

References:

- https://github.com/sensu/sensu-staging/blob/master/resources/resources.yaml#L1238-L1271

**Comment by rgeniesse** [comment]
Hm, I am not having luck testing this. If I use:

```
---
type: EventFilter
api_version: core/v2
metadata:
  name: filter-allow-always
  namespace: default
spec:
  action: allow
  expressions:
  - event.check.status == 0
  when:
    days:
      all:
      - begin: 12:00PM
        end: 6:30PM
```

And apply it to a Slack filter, I still get notified after 6:30pm.

**Comment by rgeniesse** [comment]
Further:

```
sensuctl filter info filter-allow-always --format wrapped-json
{
  "type": "EventFilter",
  "api_version": "core/v2",
  "metadata": {
    "name": "filter-allow-always",
    "namespace": "default"
  },
  "spec": {
    "action": "allow",
    "expressions": [
      "event.check.status == 0"
    ],
    "runtime_assets": null
  }
}
```

I do not see a `when` attribute here, which leads me to believe it is not being consumed when applied.   We'll need to involved eng to figure out why this isn't working.

**Comment by rgeniesse** [comment]
As testing an always allow filter by itself is not a good test as Sensu Go allows everything by default anyways, I started looking closer at the deny one. The expression works, but the when attributes are still not honored. If I have a check in warning, the follow continues to deny it even past 10:35am system time:

```
---
type: EventFilter
api_version: core/v2
metadata:
  name: filter-allow-never
  namespace: default
spec:
  action: deny
  expressions:
  - event.check.status == 1
  when:
    days:
      all:
      - begin: 12:00AM
        end: 10:35AM
      - begin: 11:00PM
        end: 1:00AM
```
