### ISSUE TITLE
Sorting on version pulldown is not quite right

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-docs#170]
![2018-02-05 at 10 12 am](https://user-images.githubusercontent.com/148017/35818400-312d191e-0a5d-11e8-9ffa-96579a6bb878.png)

**Comment by grepory** [comment]
@jamesdphillips @dabria how hard is it to pull in something that sorts versions correctly, e.g. https://github.com/quentinrossetti/version-sort

?

**Comment by dabria** [comment]
@grepory Given it's just a js library that should be easy enough. However, I'm wondering if it might not function as we'd expect because of some of the weirdness I experienced trying to get it working last time.

**Comment by jamesdphillips** [comment]
Sorting the versions with javascript after the page loads feels pretty crufty but could work. However, I think myself and Melissa had discussed before that we could probably just add a list in the config tool with the order sorted manually. Eg.

```toml
[params.products.sensu_core]
  # ...
  version_order = [
    "2.11",
    "2.10",
    "2.9",
    # , etc.
  ]
```

Alternatively we could implement semver in a templating language.. which sounds like a fun but insane exercise. 😨
