### ISSUE TITLE
Add documentation for core APIKeys API

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#1798]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

Add documentation describing the new core API datatype `APIKey`.
- Username
- CreatedAt (generated automatically)
- Name (generated UUID)
```
type: APIKey
api_version: core/v2
metadata:
  name: 83abef1e-e7d7-4beb-91fc-79ad90084d5b
spec:
  created_at: 1570640363
  username: admin
```

Reference:
https://docs.google.com/document/d/1wdfAhajJsXCEmC0vquifkbdP5O33HSPH9PbjFLC46b4/edit#
https://github.com/sensu/sensu-go/issues/3201
https://github.com/sensu/sensu-go/pull/3303
