### ISSUE TITLE
Document timezone support for cron scheduling

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#1933]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [x] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Context
https://docs.sensu.io/sensu-go/5.15/reference/checks/#cron-scheduling should have an example for using timezones in a cron string (ex: `CRON_TZ=Asia/Tokyo 0 * * * *`), as it will be supported in a future release https://github.com/sensu/sensu-go/pull/3395. See [timezone handling](https://en.wikipedia.org/wiki/Cron) for more information.

**Comment by hillaryfraley** [comment]
@nikkixdev will users have the option to use either CRON or CRON_TZ?
Or will it be only CRON_TZ (no more CRON)?

**Comment by nikkictl** [comment]
The field name `Check.Cron` is not changing. The value that a user can pass to that field now has the ability to have a timezone set. The cron string can have a prefix of `TZ=` or `CRON_TZ=` to set a timezone, but the timezone is not required.

```
type: CheckConfig
api_version: core/v2
metadata:
  name: check1
  namespace: default
spec:
  check_hooks: null
  command: hi
  cron: CRON_TZ=Asia/Tokyo 0 * * * *
  env_vars: null
  handlers: []
  high_flap_threshold: 0
  interval: 0
  low_flap_threshold: 0
  output_metric_format: ""
  output_metric_handlers: null
  proxy_entity_name: ""
  publish: true
  round_robin: false
  runtime_assets: null
  stdin: false
  subdue: null
  subscriptions:
  - sys
  timeout: 0
  ttl: 0
```
Valid cron values:
`cron: CRON_TZ=Asia/Tokyo 0 * * * *`
`cron: TZ=Asia/Tokyo 0 * * * *`
`cron: 0 * * * *`
