### ISSUE TITLE
Federation guide for the web ui

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#1942]
## This is an issue with:

- [ ] Bug (site functionality or styling)
- [ ] Errata (fix needed for doc content)
- [x] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
- [ ] Enhancement (add new site functionality)

## Context
In 5.15.0 we will ship phase 1 of the federation feature which allows users to access resources across multiple clusters via the WebUI. By using the [Federation API](https://docs.sensu.io/sensu-go/5.15/api/federation/#the-clusters-endpoint), an operator can register external clusters. A cluster does not need to be registered for the cluster that you are currently operating from (ie. self, or `local-cluster`), unless you want to configure the cluster name. The guide could be called something like "Multi-cluster visibility with Federation," and should contain screenshots of the context switcher in the WebUI showing how the federated views work.

Asymmetric JWTs must be enabled for federation to work. See https://github.com/sensu/sensu-docs/issues/1942#issuecomment-555663228.

ex. From `local-cluster`, run `sensuctl create` on the yaml below to register `us-west-2a`.
```
---
type: Cluster
api_version: federation/v1
metadata:
  name: us-west-2a
spec:
  api_urls:
  - http://10.0.0.1:8080
  - http://10.0.0.2:8080
  - http://10.0.0.3:8080
```

ex. From `local-cluster`, run `sensuctl create` on the yaml below to register an additional cluster (same API urls as `local-cluster`) and define the name as `us-west-2b`.
```
---
type: Cluster
api_version: federation/v1
metadata:
  name: us-west-2b
spec:
  api_urls:
  - http://10.0.0.4:8080
  - http://10.0.0.5:8080
  - http://10.0.0.6:8080
```
