### ISSUE TITLE
secrets/v1.Secret resource reference

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#2113]
Add reference documentation for the `secrets/v1.Secret` resource.
- `ID` is the identifying key for the provider to retrieve the secret.
- `Provider` is the name of the provider with this secret.
```
type: Secret
api_version: secrets/v1
metadata:
  name: sensu-ansible-token
  namespace: default
spec:
  id: ANSIBLE_TOKEN
  provider: env
```
