### ISSUE TITLE
secrets/v1.Provider resource reference (types Env and VaultProvider)

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#2116]
Add reference documentation for the `secrets/v1.Provider` (type `Env`) provider resource. The `Env` provider is a built-in secrets provider that can retrieve backend environment variables as secrets.

type Env
```
---
type: Env
api_version: secrets/v1
metadata:
  name: env
spec: {}
```

type VaultProvider (see https://github.com/sensu/sensu-docs/pull/2121 for more context on each VaultProvider field)
```
---
type: VaultProvider
api_version: secrets/v1
metadata:
  name: vault1
spec:
  client:
    address: https://vaultserver.example.com:8200
    token: b1g53cr3t!
    version: v1
    tls:
      ca_cert: "/etc/ssl/certs/vault_ca_cert.pem"
    max_retries: 2
    timeout: 20s
    rate_limiter:
      limit: 10
      burst: 100
```
