### ISSUE TITLE
Secrets field in checks, mutators and handlers

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#2119]
The field `secrets` has been added to checks, mutators and handlers. It is a list of `name`/`secret` pairs.
- `Name` is the name of the secret defined in the executable command.
- `Secret` is the name of the Sensu secret resource which defines how to retrieve it.

Add the following example to https://docs.sensu.io/sensu-go/latest/reference/handlers/#handler-examples
```
---
type: Handler 
api_version: core/v2 
metadata:
  name: ansible-tower
  namespace: ops
spec: 
  type: pipe
  command: sensu-ansible-handler -h $ANSIBLE_HOST -t $ANSIBLE_TOKEN
  secrets:
  - name: ANSIBLE_HOST
    secret: sensu-ansible-host
  - name: ANSIBLE_TOKEN
    secret: sensu-ansible-token
```

Add the following example to https://docs.sensu.io/sensu-go/latest/reference/checks/#check-examples
```
---
type: CheckConfig
api_version: core/v2
metadata:
  name: ping-github-api
  namespace: default
spec:
  check_hooks: null
  command: ping-github-api.sh $GITHUB_TOKEN
  secrets:
  - name: GITHUB_TOKEN
    secret: github-token-vault
```

Add the following example to https://docs.sensu.io/sensu-go/latest/reference/mutators/#mutator-examples
```
---
type: Mutator 
api_version: core/v2 
metadata:
  name: ansible-tower
  namespace: ops
spec: 
  command: sensu-ansible-mutator -h $ANSIBLE_HOST -t $ANSIBLE_TOKEN
  secrets:
  - name: ANSIBLE_HOST
    secret: sensu-ansible-host
  - name: ANSIBLE_TOKEN
    secret: sensu-ansible-token
```
