### ISSUE TITLE
YAML cron scheduling requires quotes in certain cases

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-docs#2255]
### Description

The YAML version of check resources requires quotes around cron schedule specifications when they have a leading asterisk.
### Category

This is an issue with:

- [X] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/reference/checks
### Expected behavior

Examples should work as provided.
### Current behavior

When using YAML to create a check using the cron scheduler, if the first character of the cron schedule is an asterisk (*) then it has to be quoted (either single or double quotes work) in order to be accepted.

This is most likely due to the fact that a leading asterisk in YAML is for an [alias node](https://yaml.org/spec/1.2/spec.html#alias/).
### Corrections needed

Either call out this specific case requiring quotes or have all examples for cron in YAML in quotes.
### Screenshots

Doesn't work, fails `with error parsing resources: yaml: line 8: did not find expected alphabetic or numeric character`:
```
type: CheckConfig
api_version: core/v2
metadata:
  name: interval-test
  namespace: default
spec:
  command: sleep 900
  cron: * * * * *
  publish: true
  subscriptions:
  - linux
  timeout: 300
  ttl: 0

```
Works:
```
type: CheckConfig
api_version: core/v2
metadata:
  name: interval-test
  namespace: default
spec:
  command: sleep 900
  cron: '* * * * *'
  publish: true
  subscriptions:
  - linux
  timeout: 300
  ttl: 0

```
Works:
```
type: CheckConfig
api_version: core/v2
metadata:
  name: interval-test
  namespace: default
spec:
  command: sleep 900
  cron: 0 * * * *
  publish: true
  subscriptions:
  - linux
  timeout: 300
  ttl: 0
```

### Additional context

* Browser(s) and version(s): 
* OS:
