### ISSUE TITLE
Add section of detailing web configuration feature

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-docs#2432]
### Description

Web Configuration will allow administrators to configure features and defaults in their dashboard.

An example 

```yaml
type: GlobalConfig
api_version: web/v1
metadata:
  name: default
spec:
  #
  # When one or more clusters are configured the default behaviour of the application is to omit
  # the details of the cluster the user is currently connected to. For purposes of debugging it can
  # be useful to enable.
  always_show_local_cluster: false

  #
  # Administrators can set global default preferences for all users. At this time they can tweak
  # the default theme users will see and the default amount of items a user can see on each page.
  default_preferences:
    page_size: 50
    theme: classic

  #
  # When a label or annotation contains a URL, the web app will attempt to turn it into a link or
  # and image. If administrators want they can configure which domains are valid/invalid targets.
  link_policy:
    # allow_list controls whether the list acts as an allow or deny list.
    # - as an allow list only matching URLs will be expanded
    # - as a deny list matching URLs are /not/ expanded but everything else is. 
    allow_list: true
    urls:
    - https://example.com
    - steamapp://34234234
    - //google.com
    - //*.google.com
    - //bob.local
```
