### ISSUE TITLE
Output metric tags

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-docs#2707]
### Description
A new check field, `output_metric_tags` will be added as of 6.1. This supports enriching metrics from check output metric extraction with additional metric tags.

### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [x] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages
- https://docs.sensu.io/sensu-go/latest/guides/extract-metrics-with-checks
- https://docs.sensu.io/sensu-go/latest/reference/checks/
- Anywhere that references check output metric extraction
- Any examples that use check output metric extraction

### Expected behavior
The following subset of a check uses token substitution to enrich the check output nagios metric with additional metric tags such as `instance`, `prometheus_type` and `service`.
**yaml**
```
output_metric_format: nagios_perfdata
output_metric_handlers:
  - prometheus_gateway
output_metric_tags:
  - name: instance
    value: '{{ .name }}'
  - name: prometheus_type
    value: gauge
  - name: service
    value: '{{ .labels.service }}'
```
**json**
```
  "output_metric_tags": [
    {
      "name": "foo",
      "value": "bar"
    }
  ]
```

### Current behavior
This feature will be introduced in 6.1 so no docs exist.

### Corrections needed
- `output_metric_tags` is a field in a Sensu check
- `name` and `value` make up a single tag
- `output_metric_tags` can contain multiple tags defined within the check

### Additional context
https://github.com/sensu/sensu-go/pull/3947
