### ISSUE TITLE
Cron scheduling instructions incorrect on Checks Reference

### ISSUE THREAD

**Issue by mgibson323** [sensu/sensu-docs#3245]
### Description

On the [Checks Reference page](https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/checks/#cron-scheduling), when a timezone is set for cron as per the instructions, the following error is generated when attempting to apply the check via `sensuctl`:

```
Error: error putting resource #0 with name "some-check" and namespace "default" (/api/core/v2/namespaces/default/checks/some-check): resource is invalid: check cron string is invalid
```

### Category

This is an issue with:

- [x] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [ ] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/checks/#cron-scheduling

### Expected behavior

I should be able to set the cron timezone for a check interval. 

### Current behavior

Attempts to set a timezone for cron result in an error when applying the changes with `sensuctl.` 

### Corrections needed

I tried the following but all resulted in the same error, so I think we need to clarify with engineering what the expected behavior is: 

`cron: CRON_TZ=America/Los_Angeles 0 0-15,17-23 * * *`
`cron: 'CRON_TZ=America/Los_Angeles 0 0-15,17-23 * * *'`
`cron: CRON_TZ=America/Los_Angeles '0 0-15,17-23 * * *'`

**Comment by hillaryfraley** [comment]
Hi @mgibson323 , I wasn't able to reproduce this. I ran these sensuctl commands and all successfully created the check without error:

```
sensuctl check create cron_test2 --cron "CRON_TZ=Asia/Tokyo * * * * *" --command "echo 'cron test'" -s "test"
sensuctl check create cron_test3 --cron "CRON_TZ=America/Los_Angeles 0 0-15,17-23 * * *" --command "echo 'cron test'" -s "test"
sensuctl check create cron_test4 --cron "* * * * *" --command "echo 'cron test'" -s "test"
```

```
cat << EOF | sensuctl create
---
type: CheckConfig
api_version: core/v2
metadata:
  name: cron_test5
  namespace: default
spec:
  command: echo "cron test"
  cron: 'CRON_TZ=America/Los_Angeles 0 0-15,17-23 * * *'
  handlers:
  - slack
  publish: true
  subscriptions:
  - test
EOF
```

I'm also seeing passing events for these checks. I searched Discourse for the error message you are getting and I found only one post: https://discourse.sensu.io/t/for-discussion-checks-with-time-of-day-alert-thresholds/1618/3
It seems unlikely that version is the problem here though.

I'm using the sensu-go-standalone skunkworks machine and it's running 6.4.0.

edit: I also used `sensuctl create --file` to create a check with cron scheduling from a file, and I ran this from the sensu `devel` branch (which is everything Eng has merged to `main` to date).
I used this resource def:
```
---
type: CheckConfig
api_version: core/v2
metadata:
  name: cron_test5
  namespace: default
spec:
  command: echo "cron test"
  cron: 'CRON_TZ=America/Los_Angeles 0 0-15,17-23 * * *'
  handlers:
  - slack
  publish: true
  subscriptions:
  - test
```

**Comment by mgibson323** [comment]
I'm not sure what happened when I tried this on Friday but it worked fine when I applied it just now.

Command: 
`sensuctl create -f http-check.yaml`

http-check.yaml: 

```
---
type: CheckConfig
api_version: core/v2
metadata:
  name: http-check
  namespace: default
spec:
  command: http-check --url http://sensu.io/
  cron: 'CRON_TZ=America/Los_Angeles 0 0-12,22-23 * * *'
  publish: true
  subscriptions:
  - system
  runtime_assets:
  - nixwiz/http-checks
  ```
Sensuctl output: 

```
❯ sensuctl check list --format wrapped-json
{
  "type": "CheckConfig",
  "api_version": "core/v2",
  "metadata": {
    "name": "http-check",
    "namespace": "default",
    "labels": {
      "sensu.io/managed_by": "sensuctl"
    },
    "created_by": "admin"
  },
  "spec": {
    "check_hooks": null,
    "command": "http-check --url http://sensu.io/",
    "cron": "CRON_TZ=America/Los_Angeles 0 0-12,22-23 * * *",
    "env_vars": null,
    "handlers": [],
    "high_flap_threshold": 0,
    "interval": 0,
    "low_flap_threshold": 0,
    "output_metric_format": "",
    "output_metric_handlers": null,
    "proxy_entity_name": "",
    "publish": true,
    "round_robin": false,
    "runtime_assets": [
      "nixwiz/http-checks"
    ],
    "secrets": null,
    "stdin": false,
    "subdue": null,
    "subscriptions": [
      "system"
    ],
    "timeout": 0,
    "ttl": 0
  }
}
```
