### ISSUE TITLE
Review docs for missing "Product" tag in frontmatter

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#352]
All docs should have a product tag in the frontmatter. 

**Example**

```
---
title: "Adding a Client"
product: "Sensu Core"
version: "0.29"
weight: 2
menu:
  sensu-core-0.29:
    parent: guides
---
```
