### ISSUE TITLE
Describe configuration of Postgres datastore via environment variables.

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-docs#4021]
### Category

This is an issue with:

- [ ] errata (error in doc content)
- [ ] new doc (requires a completely new doc)
- [ ] update (add missing or refresh existing content)
- [x] improvement (improve docs content or format)

### Affected pages

https://docs.sensu.io/sensu-go/latest/operations/deploy-sensu/datastore/

### Expected behavior

As part of a recent discussion with Engineering, it came to light that it's entirely possible to configure the Postgres DSN using environment variables using the existing library we utilize when making connections to postgres (see https://www.postgresql.org/docs/current/libpq-envars.html). The docs should provide _some_ example of a config illustrating the configuration via environment variables.

### Current behavior

We don't presently have any discussion or breadcrumbs of what's possible with environment variables. 

### Additional context

It is entirely possible to use something like:

**Sensu Postgres Config**
```
type: PostgresConfig
api_version: store/v1
metadata:
  name: sachshaus_postgres
spec:
  dsn: "postgresql://postgres.example.com?sslmode=disable"
  pool_size: 20
  strict: true
```

**Sensu environment variable configuration**
```
PGUSER=SOMEUSER
PGPASSWORD=SOMEPASSWORD
PGPORT=5432
PGDATABASE=sensu_events
```

This is worth highlighting for several recent use cases we've encountered.
