### ISSUE TITLE
Update frontmatter on `_index.md` pages

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-docs#624]
As a followup to #621, section index pages need to be updated to use the correct frontmatter to support ordering by weight.

Instead of `parent`:

```
[...]
 menu:
   sensu-core-1.4:
     parent: api
```

Index pages should use `identifier`:

```
[...]
 menu:
   sensu-core-1.4:
     identifier: api
```
