### ISSUE TITLE
Sensu Go types changes

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-docs#932]
Sensu Go's types will be changing after sensu/sensu-go#2400 is closed. Metadata will be specified outside of the object spec, and an api_version field will be required. E.g.:

```
type: check
api_version: core/v2
metadata:
  name: mycheck
  namespace: default
spec:
  command: mycommand
  interval: 60
  publish: true
```

## This is an issue with:

- [ ] Bug (site functionality or styling)
- [x] Errata (fix needed for doc content)
- [ ] New content (guide wanted)
- [ ] Update (Add missing or refresh existing content)
